export const Products = [
  {
    id: 1,
    name: "Regular Burger",
    price: 21,
    category_id: 1,
    img_url: "../images/locus.jpg",
  },
  {
    id: 2,
    name: "Cheese Burger",
    price: 22,
    category_id: 1,
    img_url: "../images/locus.jpg",
  },
  {
    id: 3,
    name: "Quarter Pounder",
    price: 23,
    category_id: 1,
    img_url: "../images/locus.jpg",
  },
  {
    id: 4,
    name: "Double Patty Burger",
    price: 24,
    category_id: 1,
    img_url: "../images/locus.jpg",
  },
  {
    id: 5,
    name: "1 pc chicken",
    price: 25,
    category_id: 2,
    img_url: "../images/locus.jpg",
  },
  {
    id: 6,
    name: "2 pc chicken",
    price: 26,
    category_id: 2,
    img_url: "../images/locus.jpg",
  },
  {
    id: 7,
    name: "Chicken poppers",
    price: 27,
    category_id: 2,
    img_url: "../images/locus.jpg",
  },
  {
    id: 8,
    name: "Fish fillet",
    price: 28,
    category_id: 2,
    img_url: "../images/locus.jpg",
  },
  {
    id: 9,
    name: "Hashbrown",
    price: 29,
    category_id: 3,
    img_url: "../images/locus.jpg",
  },
  {
    id: 10,
    name: "Pan cake",
    price: 30,
    category_id: 3,
    img_url: "../images/locus.jpg",
  },
  {
    id: 11,
    name: "Eggdesal",
    price: 31,
    category_id: 3,
    img_url: "../images/locus.jpg",
  },
  {
    id: 12,
    name: "Waffle",
    price: 32,
    category_id: 3,
    img_url: "../images/locus.jpg",
  },
  {
    id: 13,
    name: "Fries",
    price: 29,
    category_id: 4,
    img_url: "../images/locus.jpg",
  },
  {
    id: 14,
    name: "Quesadilla",
    price: 30,
    category_id: 4,
    img_url: "../images/locus.jpg",
  },
  {
    id: 15,
    name: "Caesar Salad",
    price: 31,
    category_id: 4,
    img_url: "../images/locus.jpg",
  },
  {
    id: 16,
    name: "Arabic Fattoush",
    price: 32,
    category_id: 4,
    img_url: "../images/locus.jpg",
  },
  {
    id: 17,
    name: "Soda",
    price: 29,
    category_id: 5,
    img_url: "../images/locus.jpg",
  },
  {
    id: 18,
    name: "Root Beer",
    price: 30,
    category_id: 5,
    img_url: "../images/locus.jpg",
  },
  {
    id: 19,
    name: "Juice",
    price: 31,
    category_id: 5,
    img_url: "../images/locus.jpg",
  },
  {
    id: 20,
    name: "Coffee",
    price: 32,
    category_id: 5,
    img_url: "../images/locus.jpg",
  },
  {
    id: 21,
    name: "Sundae",
    price: 29,
    category_id: 6,
    img_url: "../images/locus.jpg",
  },
  {
    id: 22,
    name: "Float",
    price: 30,
    category_id: 6,
    img_url: "../images/locus.jpg",
  },
  {
    id: 23,
    name: "Salted Caramel",
    price: 31,
    category_id: 6,
    img_url: "../images/locus.jpg",
  },
  {
    id: 24,
    name: "Crusher",
    price: 32,
    category_id: 6,
    img_url: "../images/locus.jpg",
  },
];
